name: Publish Docker image
on:
  push:
    tags:
    - v[0-9]*
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Set tag version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:openldap-${{ steps.vars.outputs.tag }}
          target: cli
